services:
  - type: web
    name: healthmate-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: OPENAI_API_KEY
        value: @dmin1@3
      - key: MONGO_URI
        value: healthmate
      - key: PORT
        value: 5000
